Illegal State Exception Fix: Removed lifecycleRegistry States
spoonconsulting/cordova-plugin-simple-camera-preview pull request #38
Opened 2021-12-14 10:32 UTC by zafirskthelifehacker

2021-12-14 11:57 UTC, ombr requested changes

2021-12-14 11:57 UTC, ombr commented on src/android/CameraPreviewFragment.java
> -
Tu peux complètement supprimer la fonction non ?

2021-12-14 14:14 UTC, zafirskthelifehacker commented on src/android/CameraPreviewFragment.java
> -
@ombr J'ai supprime la fonction. Pas d'erreur.

2021-12-16 07:41 UTC, dinitri-ragoo approved these changes

2021-12-16 13:43 UTC, merged