check if flash unit is present
spoonconsulting/cordova-plugin-simple-camera-preview pull request #64
Opened 2023-01-04 05:49 UTC by parveshneedhoo

Added code to check if flash unit is present before toggling torch

2023-01-06 07:45 UTC, dinitri requested changes
reviewed android part only

2023-01-06 07:45 UTC, dinitri commented on src/android/SimpleCameraPreview.java
> +import android.widget.Toast;
```suggestion
```

2023-01-06 07:45 UTC, dinitri commented on src/android/CameraPreviewFragment.java
> +        return;
```suggestion
        flashCallback.onResult(camera.getCameraInfo().hasFlashUnit());
```
?

2023-01-06 07:45 UTC, dinitri commented on src/android/SimpleCameraPreview.java
> +
```suggestion
            PluginResult pluginResult = new PluginResult(PluginResult.Status.OK, result);
```
can keep the name as pluginResult, it's a local variable

2023-01-06 07:45 UTC, dinitri commented on src/android/SimpleCameraPreview.java
> +            pluginResult1.setKeepCallback(true);
why keep callback true ?

2023-01-06 14:45 UTC, zfir commented on src/ios/SimpleCameraPreview.m
> +    }
```suggestion
      pluginResult = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsBool:hasTorch];
```

2023-01-09 11:06 UTC, zfir approved these changes

2023-01-09 11:06 UTC, zfir commented on src/android/CameraPreviewFragment.java
> +interface FlashCallback {
```suggestion
interface HasFlashCallback {
```
?

2023-01-10 10:42 UTC, zfir approved these changes

2023-01-10 10:42 UTC, zfir commented on src/android/CameraPreviewFragment.java
> +    public void hasFlash(HasFlashCallback flashCallback) {
```suggestion
    public void hasFlash(HasFlashCallback hasFlashCallback) {
```

2023-01-13 14:15 UTC, dinitri reviewed
just one question, it looks good

2023-01-13 14:15 UTC, dinitri commented on src/ios/SimpleCameraPreview.m
> +        if ([device hasTorch]) {
i see the hasTorch method too when looking at apple's documentation, should we cater for the hasTorch method too ?  or hasTorch is enough? @zfir just a question

2023-01-20 11:39 UTC, dinitri approved these changes

2023-01-30 13:29 UTC, merged